go_binary(
    name = "hello",
    srcs = ["hello.go"],
)

go_binary(
    name = "packages",
    srcs = ["packages.go"],
)

go_binary(
    name = "functions",
    srcs = ["functions.go"],
)

go_binary(
    name = "variables",
    srcs = ["variables.go"],
)
