go_binary(
    name = "basic-types",
    srcs = ["basic-types.go"],
)

go_binary(
    name = "deferred-functions",
    srcs = ["deferred-functions.go"],
)

go_binary(
    name = "for-loop",
    srcs = ["for-loop.go"],
)

go_binary(
    name = "switch-test",
    srcs = ["switch-test.go"],
)

go_binary(
    name = "hello",
    srcs = ["hello.go"],
)

go_binary(
    name = "packages",
    srcs = ["packages.go"],
)

go_binary(
    name = "functions",
    srcs = ["functions.go"],
)

go_binary(
    name = "variables",
    srcs = ["variables.go"],
)

go_binary(
    name = "numeric-constant",
    srcs = ["numeric-constant.go"],
)

go_binary(
    name = "array-tutorials",
    srcs = ["array-tutorials.go"],
)

go_binary(
    name = "pointers",
    srcs = ["pointers.go"],
)

go_binary(
    name = "structs",
    srcs = ["structs.go"],
)

go_binary(
    name = "go-conditions",
    srcs = ["go-conditions.go"],
)

go_binary(
    name = "closures-fib",
    srcs = ["closures-fib.go"],
)

go_binary(
    name = "exercise-slices",
    srcs = ["exercise-slices.go"],
)

go_binary(
    name = "matrix-via-slice",
    srcs = ["matrix-via-slice.go"],
)

go_binary(
    name = "slice-literals",
    srcs = ["slice-literals.go"],
)

go_binary(
    name = "slice-via-make",
    srcs = ["slice-via-make.go"],
)

go_binary(
    name = "slices-len-cap",
    srcs = ["slices-len-cap.go"],
)

go_binary(
    name = "function-values",
    srcs = ["function-values.go"],
)

go_binary(
    name = "map-basics",
    srcs = ["map-basics.go"],
)

go_binary(
    name = "word-count",
    srcs = ["word-count.go"],
)
