go_binary(
    name = "basic-types",
    srcs = ["basic-types.go"],
)

go_binary(
    name = "deferred-functions",
    srcs = ["deferred-functions.go"],
)

go_binary(
    name = "for-loop",
    srcs = ["for-loop.go"],
)

go_binary(
    name = "switch-test",
    srcs = ["switch-test.go"],
)

go_binary(
    name = "hello",
    srcs = ["hello.go"],
)

go_binary(
    name = "packages",
    srcs = ["packages.go"],
)

go_binary(
    name = "functions",
    srcs = ["functions.go"],
)

go_binary(
    name = "variables",
    srcs = ["variables.go"],
)

go_binary(
    name = "numeric-constant",
    srcs = ["numeric-constant.go"],
)
